using System.Collections.Generic;

namespace SingleMachineTotalWeightedTardinessProblem
{
    class PopulationByMethod : IPopulationGenerator
    {
        public AMethod GeneratingMethod { get; set; }

        public PopulationByMethod(AMethod generatingMethod)
        {
            GeneratingMethod = generatingMethod;
        }

        public List<Codestring> GetPopulation(int sizeOfPopulation)
        {
            List<Codestring> Population = new List<Codestring>();
            for (int i = 0; i < sizeOfPopulation; i++)
            {
                Population.Add(GenerateCodestring(GeneratingMethod));
            }

            return Population;
        }

        private Codestring GenerateCodestring(AMethod generator)
        {
            return new Codestring(generator.GetSolution(), generator.Sample);
        }

        public override string ToString()
        {
            return "Population generated by provided method";
        }
    }
}
